---
title: "Selected Presentations"
output: html_document
---

- Strategies for Successfully Scoping and Tracking Collaborative Statistical Work. Topic-contributed Panel at JSM 2023 with Alex Hanlon, Emily Griffith, Ryan Peterson, and Julia Sharp.

- Working with statisticians: Perceptions of practicing statisticians on their most successful collaborations. ACTStat 2023. 

-	Detecting Interactions in R. Invited speed talk, National Center for Health Statistics and the Center for Disease Control, Virtual, May 2023. 

-	Successful Approaches to Teaching Statistical Consulting. Invited Panel Discussion led by Julia Sharp. The ASA Section on Teaching of Statistics in the Health Sciences Webinar, Virtual, May 2023. [Watch](https://www.youtube.com/watch?v=sFCD6BE8aLk)

- Selection tools for handling suspected signal heterogeneity in covariates with applications to interactions and high-dimensional time series, Invited Seminar, Department of Biostatistics and Data Science, Wake Forest University School of Medicine, March 2023.

-	The Sparsity-Ranked Lasso, Invited Seminar, Department of Biostatistics and Informatics, University of Colorado, February 2023. 

-	Reaping What You SOW, Invited Panel Session, Conference on Statistical Practice, San Francisco, CA, February 2023. 

-	An Introduction to Biomedical Applications of Big Data, Machine Learning, and Artificial Intelligence. Invited Seminar. Big Data Seminar Series, Colorado Clinical and Translational Science Institute, University of Colorado, November 2022. 

- Fast, effective, and coherent time series modeling with the sparsity-ranked lasso: the srlTS R package. ASA Colorado/Wyoming Chapter Annual Meeting. Aurora, CO. November 2022. 

- Integrating public-use data for policy research: modeling city-specific trends in pollution and mobility through the COVID-19 pandemic. ColoradoSPH Research Exchange, Aurora, CO. September 2022.

- Can a new transparent algorithm predict better than its black-box counterparts? Symposium on Data Science and Statistics, Annual Conference, Pittsburgh, PA. June 2022. 

-	Aggregating penalized regression coefficients after multiple imputation for urgent and effective prediction of intubation in patients with severe COVID-19. ACTStat 2021 Annual Meeting, Virtual. Early Career Award winner.

-	Penalized Regression and Multiple Imputation: A Simple Aggregation Rule That Works Surprisingly Well. Joint Statistical Meetings, Virtual Conference, 2021.

- "But what about interactions, are any of those significant?" Resolving the collaborative nightmare of covariate interactions using regularization. International Biometric Conference. Virtual conference, 2020. (Contributed poster; won Best Poster Award)  

-	Predictive Modeling:  From Simple to Complex and Transparent to Opaque, A Debate of Two Extremes. Department of Biostatistics & Informatics, Colorado School of Public Health, University of Colorado, November 2019. 

- Ranked Sparsity Methods for Transparent Model Selection. Joint Statistical Meetings, Vancouver, British Columbia, Canada. August 2018. 

-	Multistate Modeling in Clinical Trials: how to plan, power, and analyze multistate studies using the Multistate Simulation Designer. Cancer Center Special Topics Seminar, Mayo Clinic, Rochester, MN, 2017. 

-	Parkinson’s Progression Markers Initiative: filtering noisy outcomes and prediction-guided inference. Departmental Seminar, University of Iowa. Iowa City, IA. December 2016.


